// <auto-generated />
using FAQpage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FAQpage.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191115135526_SeedDatabase")]
    partial class SeedDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FAQpage.Models.SporsmalOgSvar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Sporsmal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Svar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SporsmalerOgSvar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Sporsmal = "Hvor kan jeg kjøpe billetter?",
                            Svar = "Du kan kjøpe billetter fra vår nettside eller så kan kjøpe billett fra billettautomaten som er lokalisert på togstasjonene"
                        },
                        new
                        {
                            Id = 2,
                            Sporsmal = "Hvordan kjøper jeg periodebillett?",
                            Svar = "Du kan også kjøpe periodebillett på vår nettside"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
